# Generated by Django 4.2 on 2023-06-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_day",
            field=models.CharField(max_length=5),
        ),
    ]
