# Generated by Django 4.2 on 2023-06-14 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=10)),
                ("category", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=45)),
                ("content", models.CharField(max_length=255)),
                ("registered_time", models.DateTimeField()),
                ("updated_time", models.DateTimeField()),
                ("image", models.CharField(blank=True, max_length=45, null=True)),
                ("video", models.CharField(blank=True, max_length=45, null=True)),
                ("recommendation", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_post",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
