# Generated by Django 4.2 on 2023-06-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.BigIntegerField()),
                ("user_id", models.BigIntegerField()),
                ("kind", models.CharField(max_length=10)),
                ("category", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=45)),
                ("content", models.CharField(max_length=255)),
                ("registered_time", models.DateTimeField()),
                ("updated_time", models.DateTimeField()),
                ("image", models.CharField(max_length=45)),
                ("video", models.CharField(max_length=45)),
                ("recommendation", models.IntegerField()),
            ],
        ),
    ]
