# Generated by Django 4.2 on 2023-06-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="post_videos/"),
        ),
    ]
