# Generated by Django 4.2 on 2023-06-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.CharField(max_length=45, null=True),
        ),
    ]
