# Generated by Django 4.2 on 2023-06-13 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registered_time", models.DateTimeField()),
                ("updated_time", models.DateTimeField()),
                ("content", models.CharField(max_length=255)),
                ("video", models.CharField(max_length=45)),
                ("day", models.DateField()),
                ("thumbnail", models.CharField(max_length=45)),
                ("bookmark", models.BooleanField(default=False)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pet.pet"
                    ),
                ),
            ],
        ),
    ]
