# Generated by Django 4.2 on 2023-06-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="diary_videos/"),
        ),
    ]
