# Generated by Django 4.2 on 2023-06-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0002_alter_diary_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="content",
            field=models.CharField(max_length=1024),
        ),
    ]
