# Generated by Django 4.2 on 2023-06-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0004_alter_diary_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="thumbnail",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="diary_images/"
            ),
        ),
        migrations.AlterField(
            model_name="diary",
            name="video",
            field=models.FileField(
                blank=True, max_length=500, null=True, upload_to="diary_videos/"
            ),
        ),
    ]
