# Generated by Django 4.2 on 2023-06-14 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="personality",
        ),
        migrations.AddField(
            model_name="personality",
            name="pet",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="pet.pet"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="personality",
            name="activity",
            field=models.CharField(choices=[("A", "모험"), ("L", "안주")], max_length=1),
        ),
        migrations.AlterField(
            model_name="personality",
            name="dependence",
            field=models.CharField(choices=[("T", "신뢰"), ("N", "필요")], max_length=1),
        ),
        migrations.AlterField(
            model_name="personality",
            name="proto_dog",
            field=models.CharField(choices=[("C", "교감"), ("W", "본능")], max_length=1),
        ),
        migrations.AlterField(
            model_name="personality",
            name="relationship",
            field=models.CharField(choices=[("E", "외향"), ("I", "내향")], max_length=1),
        ),
        migrations.AlterField(
            model_name="pet",
            name="gender",
            field=models.CharField(choices=[("W", "암컷"), ("M", "수컷")], max_length=1),
        ),
        migrations.AlterField(
            model_name="pet",
            name="kind",
            field=models.CharField(
                choices=[("Cat", "고양이"), ("Dog", "강아지")], max_length=3
            ),
        ),
    ]
