# Generated by Django 4.2 on 2023-06-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0002_remove_pet_personality_personality_pet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="image",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="is_neutered",
            field=models.BooleanField(default=False),
        ),
    ]
