# Generated by Django 4.2 on 2023-06-14 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
        ("post_liked", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postliked",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_likes",
                to="post.post",
            ),
        ),
    ]
