# Generated by Django 4.2 on 2023-06-14 01:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post_liked", "0002_alter_postliked_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postliked",
            name="is_liked",
        ),
    ]
